### ISSUE TITLE
Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: UNION types integer and character varying cannot be matched   Position: 325

### ISSUE THREAD

**Issue by lofung** [ohdsi-studies/LegendT2dm#15]
Similar to last issue #13 , which is 'solved' by changing our source id columns of our database (which does not make sense, wasn't the source id and the source value columns are not recommended for analysis)?

This time, we have an issue in the middle of the analysis.

![image](https://user-images.githubusercontent.com/53417646/149318837-59fc8bf2-af29-4458-923b-48de642acd19.png)

Note 
````
Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: UNION types integer and character varying cannot be matched
  Position: 325
An error report has been created at  D:/OHDSI-LegendT2DM-THIN/LegendT2dm/errorReportSql.txt
````

Below are the errorReportR.txt
````
Thread: Main
Message:  Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: UNION types integer and character varying cannot be matched   Position: 325 An error report has been created at  D:/OHDSI-LegendT2DM-THIN/LegendT2dm/errorReportSql.txt [90mRun `rlang::last_error()` to see where the error occurred.[39m 
Level:  FATAL
Time:  2022-01-13 18:19:06

Stack trace:
14: stop(fallback)
13: signal_abort(cnd)
12: abort(paste("Error executing SQL:", message, paste("An error report has been created at ", f
11: .createErrorReport(connection@dbms, err$message, sqlStatement, errorReportFile)
10: value[[3]](cond)
9: tryCatchOne(expr, names, parentenv, handlers[[1]])
8: tryCatchList(expr, classes, parentenv, handlers)
7: tryCatch({
    startQuery <- Sys.time()
    lowLevelExecuteSql(connection, sqlStatement)
   
6: DatabaseConnector::executeSql(connection, sql)
5: createConceptCountsTable(connection = connection, cdmDatabaseSchema = cdmDatabaseSchema, tem
4: runConceptSetDiagnostics(connection = connection, tempEmulationSchema = tempEmulationSchema,
3: CohortDiagnostics.R#30: CohortDiagnostics::runCohortDiagnostics(packageName = "LegendT2dm", 
2: Assessment.R#103: runExposureCohortDiagnostics(connectionDetails, cdmDatabaseSchema, vocabul
1: assessPhenotypes(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchem

R version:
R version 4.0.5 (2021-03-31)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- LegendT2dm (0.0.1)
- DatabaseConnector (4.0.2)

````

errorReportSql.txt
````
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "#"
  Position: 15

SQL:
SELECT * FROM #exposure_cohorts;

R version:
R version 4.0.5 (2021-03-31)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- LegendT2dm (0.0.1)
- DatabaseConnector (4.0.2)
````

Could it have to do with a null cdm_source table?

What are they comparing when a SQL does not match that deep into the script?

Thanks

**Comment by lofung** [comment]
The sql error file says that it is a syntax error for ````SELECT * FROM #exposure_cohorts;````

but r error file says it is a type matching issue, that two error reports do not seem to make sense either-

**Comment by lofung** [comment]
can we solve it this way but how to we solve it for LegendT2DM script?

https://stackoverflow.com/questions/63997315/union-types-text-and-bigint-cannot-be-matched

**Comment by lofung** [comment]
assessmentLog.txt

![image](https://user-images.githubusercontent.com/53417646/149322521-c54cbb4a-0e55-44bc-8829-e741dc19ad96.png)


````
2022-01-13 18:19:06	[Main thread]	INFO	CohortDiagnostics	createConceptCountsTable	Creating internal concept counts table

````

is the last line before it hits the designated error.

**Comment by msuchard** [comment]
@lofung -- a colleague recently tried the LEGEND-T2DM study code against an postgresql database, and everything appears to work.   My best guess is that your tables do not follow the OMOP CDM 5.3 specification.    One of these requirements is that `cdm_source` cannot be null.   You can find the specification here (https://github.com/ohdsi/commondatamodel)

The LEGEND-T2DM package depends on many OHDSI packages.  So narrowing now your format issues using LEGEND is probably not the easiest.  I'd recommend first running something like `DataQualityDashboard` and a small characterization study first.
