### ISSUE TITLE
R Version Clarification

### ISSUE THREAD

**Issue by jkylearmstrong** [ohdsi-studies/LegendT2dm#9]
Additional clarification requested: is R version 4.0.5 required as listed on the README or will any R (>= 4.0) work as detailed in  [https://github.com/ohdsi-studies/LegendT2dm/blob/master/DESCRIPTION]? 

Is RStudio required? Or are we able to build package with just R?

**Comment by lofung** [comment]
i have had colleagues who used 4.1.0 and didnt work. have to downgrade to 4.0.5.

in the progress i have downgraded to 405 also with other things, but i didnt verify if 405/410 has contributed to the issue.

**Comment by jkylearmstrong** [comment]
@lofung - Thanks. That's helpful.  Do you happen to know if RStudio is required as well? Or is base R sufficient?

**Comment by msuchard** [comment]
`RStudio` is _not_ necessary.     The `renv.lock` specifies `R 4.0.*` and this package remains untested under >= 4.1

**Comment by lofung** [comment]
rstudio is only an skin-ish ide i dont think it contributes to the problem

you can use something like vscode
